-- Run this in the BBCal Supabase project's SQL editor.
create table if not exists public.calendar_todo_links (
  id bigint generated by default as identity primary key,
  todo_list_id uuid not null,
  todo_share_code uuid not null,
  start_slot bigint not null,
  end_slot bigint not null,
  created_at timestamptz not null default now(),
  constraint calendar_todo_links_valid_range check (end_slot > start_slot)
);

create index if not exists calendar_todo_links_range_idx
  on public.calendar_todo_links(start_slot, end_slot);

alter table public.calendar_todo_links disable row level security;

grant select, insert, update, delete
  on public.calendar_todo_links to anon, authenticated;

grant usage, select
  on sequence public.calendar_todo_links_id_seq to anon, authenticated;
